# Generated by Django 3.1.6 on 2021-05-05 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_rating', models.CharField(default='4/5', max_length=200)),
                ('place_change', models.TextField(default='No changes submitted yet.')),
                ('submitting_user', models.CharField(default='default submitter', max_length=200)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time submitted')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('num_submissions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default='default place name', max_length=200)),
                ('place_address', models.CharField(default='default place address', max_length=200)),
                ('google_place_id', models.TextField(default='default google place id')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.change')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='change',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.place'),
        ),
    ]
